from djongo import models

class InverterData(models.Model):
    """
    Represents a single data record from an inverter device, stored in a MongoDB collection.

    This model captures various electrical and operational metrics collected from an inverter,
    including voltage, current, power, frequency, and temperature values, both on the AC and DC sides.

    Attributes:
        _id (ObjectIdField): Primary key autogenerated by MongoDB.
        send_server (BooleanField): Indicates whether the data should be sent to the server.
        DATE (DateTimeField): Timestamp of when the data was recorded.
        TP_I (IntegerField): Type or identifier of the transmission point.
        OPERATION_STATE (IntegerField): Current operational state of the inverter.
        GENERATION (FloatField): Energy generation value.
        POWER_FACTOR (FloatField): Power factor of the inverter.
        REACTIVE_POWER (FloatField): Reactive power measurement.
        POWER_SNAPSHOT (FloatField): Instantaneous power measurement.
        VOLTAGE_1_DC to VOLTAGE_4_DC (FloatField): DC voltage readings from different input channels.
        CURRENT_1_DC to CURRENT_4_DC (FloatField): DC current readings from different input channels.
        VOLTAGE_1_AC to VOLTAGE_3_AC (FloatField): AC voltage readings from each phase.
        CURRENT_1_AC to CURRENT_3_AC (FloatField): AC current readings from each phase.
        TEMPERATURE_INVERTER (FloatField): Internal temperature of the inverter.
        GRID_FREQUENCY (FloatField): Frequency of the connected grid.
        id_slave (IntegerField): Identifier of the slave device.
        device_type (CharField): Type or model of the inverter device.
        sent (BooleanField): Indicates whether this record has been successfully sent to the server.

    Meta:
        db_table (str): Name of the MongoDB collection ('inverters').
        managed (bool): Indicates Django should manage the table's lifecycle.

    Returns:
        str: A string representation of the inverter data entry.
    """
    _id = models.ObjectIdField(primary_key=True)  # Único campo autogenerado
    send_server = models.BooleanField(default=True)
    DATE = models.DateTimeField()
    TP_I = models.IntegerField()
    OPERATION_STATE = models.IntegerField()
    GENERATION = models.FloatField()
    POWER_FACTOR = models.FloatField()
    REACTIVE_POWER = models.FloatField()
    POWER_SNAPSHOT = models.FloatField()
    VOLTAGE_1_DC = models.FloatField()
    VOLTAGE_2_DC = models.FloatField()
    VOLTAGE_3_DC = models.FloatField()
    VOLTAGE_4_DC = models.FloatField()
    CURRENT_1_DC = models.FloatField()
    CURRENT_2_DC = models.FloatField()
    CURRENT_3_DC = models.FloatField()
    CURRENT_4_DC = models.FloatField()
    VOLTAGE_1_AC = models.FloatField()
    VOLTAGE_2_AC = models.FloatField()
    VOLTAGE_3_AC = models.FloatField()
    CURRENT_1_AC = models.FloatField()
    CURRENT_2_AC = models.FloatField()
    CURRENT_3_AC = models.FloatField()
    TEMPERATURE_INVERTER = models.FloatField()
    GRID_FREQUENCY = models.FloatField()
    id_slave = models.IntegerField()
    device_type = models.CharField(max_length=255)
    sent = models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = "inverters"

    def __str__(self):
        return f"Inverter Data {self._id}"
